# Generated by Django 4.2.1 on 2023-06-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='ExperienceWithArbitrationText',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participants',
            name='ExperienceWithCourtProceedingsText',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participants',
            name='ExperienceWithMediationText',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participants',
            name='ST1SelectionText',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participants',
            name='ST2SelectionText',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participants',
            name='ST3SelectionText',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
