# Generated by Django 4.2.1 on 2023-06-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyAPI', '0002_alter_participants_experiencewitharbitrationtext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='MaritalStatus',
            field=models.CharField(choices=[('SI', 'Single'), ('MA', 'Married'), ('SE', 'Separated'), ('DI', 'Divorced'), ('WI', 'Widowed')], max_length=2),
        ),
    ]
