# Generated by Django 4.2.1 on 2023-07-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyAPI', '0003_alter_participants_maritalstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='Age',
            field=models.CharField(choices=[('0', 'External'), ('1', '18 - 29'), ('2', '30 - 39'), ('3', '40 - 49'), ('4', '50 - 59'), ('5', '60 +')], default='0', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participants',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('E', 'External')], default='E', max_length=1),
            preserve_default=False,
        ),
    ]
