# Generated by Django 4.2.1 on 2023-07-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyAPI', '0004_participants_age_participants_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='TK11',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK12',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK13',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK14',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK15',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK16',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK17',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK18',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK19',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK20',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK21',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK22',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK23',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK24',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK25',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK26',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK27',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK28',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK29',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='TK30',
        ),
    ]
