# Generated by Django 4.2.1 on 2023-07-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyAPI', '0005_remove_participants_tk11_remove_participants_tk12_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='NumberOfGrandChildren',
        ),
    ]
