# Generated by Django 4.2.1 on 2023-08-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyAPI', '0006_remove_participants_numberofgrandchildren'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='ST3Classification',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3ControlOfOutcome',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3ControlOfProcess',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3CreatePrecedent',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3CreativeSolution',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3EnsuringCompliance',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3Feelings',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3ImproveUnderstanding',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3MaintainImproveRelationship',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3MinMaxCompensation',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3MinimizeCosts',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3NeutralOpinion',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3Number',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3Privacy',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3PublicVindication',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3RecognitionApology',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3Selection',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3SelectionText',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3ShiftResponsibility',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3Speed',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3StrengthPosition',
        ),
        migrations.RemoveField(
            model_name='participants',
            name='ST3TransformationOfTheParties',
        ),
    ]
