# Generated by Django 4.2.1 on 2023-08-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyAPI', '0007_remove_participants_st3classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='ST3Classification',
            field=models.CharField(choices=[('MC', 'Major Conflict'), ('SD', 'Serious Dispute'), ('CD', 'Common Dispute'), ('MU', 'Misunderstanding'), ('MD', 'Minor Disagreement')], default='XX', max_length=2),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3ControlOfOutcome',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3ControlOfProcess',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3CreatePrecedent',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3CreativeSolution',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3EnsuringCompliance',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3Feelings',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3ImproveUnderstanding',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3MaintainImproveRelationship',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3MinMaxCompensation',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3MinimizeCosts',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3NeutralOpinion',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3Number',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3Privacy',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3PublicVindication',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3RecognitionApology',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3Selection',
            field=models.CharField(choices=[('AD', 'Adjudication'), ('AR', 'Arbitration'), ('ME', 'Mediation'), ('NE', 'Negotiation'), ('LG', 'Let go'), ('PC', 'Public Complaint')], default='XX', max_length=2),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3SelectionText',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3ShiftResponsibility',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3Speed',
            field=models.PositiveSmallIntegerField(default=99),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3StrengthPosition',
            field=models.CharField(choices=[('ST', 'Stronger'), ('WE', 'Weaker')], default='XX', max_length=2),
        ),
        migrations.AddField(
            model_name='participants',
            name='ST3TransformationOfTheParties',
            field=models.PositiveSmallIntegerField(default=99),
        ),
    ]
