# Generated by Django 4.2.1 on 2023-08-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SurveyAPI', '0008_participants_st3classification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='Country',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
